# Site settings
title: Vlor Blog
#filing: 粤ICP备17125314号
SEOTitle: Vlor的博客 | Vlor Blog
header-img: img/post-bg-taylorswift9.jpg
email: 614316365@qq.com
description: "这家伙总以为自己是个天才，实际并不比别人聪明多少！"
keyword: "MrChang, MrChangBlog, MrChang的博客, Java Dev ,changdaye , mrchang "
url: "http://vlor.top"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/VincentZhangy/vlor.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "这家伙总以为自己是个天才，实际并不比别人聪明多少！"
sidebar-avatar: /img/about-BY-gentle.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`

##cdn
cdn: 阿里云提供CDN加速服务
cdnUrl: https://www.aliyun.com/product/cdn?spm=5176.7933691.765261.407.79w7vI

githubPage: GitHubPage提供构建部署服务
githubPageUrl: https://pages.github.com/

# SNS settings
RSS: false
weibo_username:     5657775703
zhihu_username:     zhang-yun-97-97
github_username:    VincentZhangy
#facebook_username:  baiying.qiu.7
jianshu_username:
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: VincentZhangy

# 多说 将于2017年6月1日正式关停服务，建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Duoshuo settings
# duoshuo_username: changdaye
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: d500fea6bca5955e5a2eb8656d467574

# Google Analytics
ga_track_id: 'UA-106020704-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: false                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "MrChang Blog",
        href: "http://blog.jetbrains.org.cn/"
    },{
        title: "jianghoufeng",
        href: "https://github.com/ophina"
    },{
        title: "hsweb",
        href: "https://github.com/zhou-hao"
    },{
             title: "憧憬点滴记忆",
             href: "https://www.licoy.cn/"
    },{
             title: "少将博客",
             href: "https://www.whatled.com/"
    },{
             title: "BMAdmin 企业后台管理系统",
             href: "http://www.bmadmin.com/"
    },{
             title: "夜村溪",
             href: "https://www.rojackse.top/"
    },{
             title: "忘lele",
             href: "https://gmle.club/"
    },{
             title: "李牧牧",
             href: "http://limumu.me/"
    },{
             title: "mdtr2pdf",
             href: "http://www.mdtr2pdf.com/"
    },{
             title: "少将博客",
             href: "https://jiangshaobo.cn/"
    }

]

